Raise required compiler to rust 1.74
    error[E0552]: unrecognized representation hint
     --> tests/doc/src/lib.rs:3:1
      |
    3 | #[phantom]
      | ^^^^^^^^^^
      |
      = help: valid reprs are `C`, `align`, `packed`, `transparent`, `simd`, `i8`, `u8`, `i16`, `u16`, `i32`, `u32`, `i64`, `u64`, `i128`, `u128`, `isize`, `usize`
      = note: this error originates in the attribute macro `phantom` (in Nightly builds, run with -Z macro-backtrace for more info)