Raise minimum tested toolchain to 1.36
Required by the dev-dependency on trybuild and transitively on
once_cell, itoa, and ryu.

    error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
      --> github.com-1ecc6299db9ec823/itoa-1.0.1/src/lib.rs:44:23
       |
    44 | use core::mem::{self, MaybeUninit};
       |                       ^^^^^^^^^^^

    error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
      --> github.com-1ecc6299db9ec823/itoa-1.0.1/src/lib.rs:58:13
       |
    58 |     bytes: [MaybeUninit<u8>; I128_MAX_LEN],
       |             ^^^^^^^^^^^^^^^

    error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
      --> github.com-1ecc6299db9ec823/itoa-1.0.1/src/lib.rs:80:22
       |
    80 |         let bytes = [MaybeUninit::<u8>::uninit(); I128_MAX_LEN];
       |                      ^^^^^^^^^^^^^^^^^^^^^^^^^

    error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
      --> github.com-1ecc6299db9ec823/itoa-1.0.1/src/lib.rs:88:45
       |
    88 |             &mut *(&mut self.bytes as *mut [MaybeUninit<u8>; I128_MAX_LEN]
       |                                             ^^^^^^^^^^^^^^^

    error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
       --> github.com-1ecc6299db9ec823/itoa-1.0.1/src/lib.rs:121:28
        |
    121 |               type Buffer = [MaybeUninit<u8>; $max_len];
        |                              ^^^^^^^^^^^^^^^
    ...
    197 | / impl_Integer!(
    198 | |     I8_MAX_LEN => i8,
    199 | |     U8_MAX_LEN => u8,
    200 | |     I16_MAX_LEN => i16,
    ...   |
    203 | |     U32_MAX_LEN => u32
    204 | |     as u32);
        | |____________- in this macro invocation

    error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
       --> github.com-1ecc6299db9ec823/itoa-1.0.1/src/lib.rs:125:39
        |
    125 |               fn write(self, buf: &mut [MaybeUninit<u8>; $max_len]) -> &str {
        |                                         ^^^^^^^^^^^^^^^
    ...
    197 | / impl_Integer!(
    198 | |     I8_MAX_LEN => i8,
    199 | |     U8_MAX_LEN => u8,
    200 | |     I16_MAX_LEN => i16,
    ...   |
    203 | |     U32_MAX_LEN => u32
    204 | |     as u32);
        | |____________- in this macro invocation

    error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
       --> github.com-1ecc6299db9ec823/itoa-1.0.1/src/lib.rs:121:28
        |
    121 |             type Buffer = [MaybeUninit<u8>; $max_len];
        |                            ^^^^^^^^^^^^^^^
    ...
    206 | impl_Integer!(I64_MAX_LEN => i64, U64_MAX_LEN => u64 as u64);
        | ------------------------------------------------------------- in this macro invocation

    error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
       --> github.com-1ecc6299db9ec823/itoa-1.0.1/src/lib.rs:125:39
        |
    125 |             fn write(self, buf: &mut [MaybeUninit<u8>; $max_len]) -> &str {
        |                                       ^^^^^^^^^^^^^^^
    ...
    206 | impl_Integer!(I64_MAX_LEN => i64, U64_MAX_LEN => u64 as u64);
        | ------------------------------------------------------------- in this macro invocation

    error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
       --> github.com-1ecc6299db9ec823/itoa-1.0.1/src/lib.rs:121:28
        |
    121 |             type Buffer = [MaybeUninit<u8>; $max_len];
        |                            ^^^^^^^^^^^^^^^
    ...
    215 | impl_Integer!(I64_MAX_LEN => isize, U64_MAX_LEN => usize as u64);
        | ----------------------------------------------------------------- in this macro invocation

    error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
       --> github.com-1ecc6299db9ec823/itoa-1.0.1/src/lib.rs:125:39
        |
    125 |             fn write(self, buf: &mut [MaybeUninit<u8>; $max_len]) -> &str {
        |                                       ^^^^^^^^^^^^^^^
    ...
    215 | impl_Integer!(I64_MAX_LEN => isize, U64_MAX_LEN => usize as u64);
        | ----------------------------------------------------------------- in this macro invocation

    error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
       --> github.com-1ecc6299db9ec823/itoa-1.0.1/src/lib.rs:222:28
        |
    222 |             type Buffer = [MaybeUninit<u8>; $max_len];
        |                            ^^^^^^^^^^^^^^^
    ...
    284 | impl_Integer128!(I128_MAX_LEN => i128, U128_MAX_LEN => u128);
        | ------------------------------------------------------------- in this macro invocation

    error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
       --> github.com-1ecc6299db9ec823/itoa-1.0.1/src/lib.rs:226:39
        |
    226 |             fn write(self, buf: &mut [MaybeUninit<u8>; $max_len]) -> &str {
        |                                       ^^^^^^^^^^^^^^^
    ...
    284 | impl_Integer128!(I128_MAX_LEN => i128, U128_MAX_LEN => u128);
        | ------------------------------------------------------------- in this macro invocation

    error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
       --> github.com-1ecc6299db9ec823/itoa-1.0.1/src/lib.rs:240:85
        |
    240 |                     let buf1 = buf_ptr.offset(curr - U64_MAX_LEN as isize) as *mut [MaybeUninit<u8>; U64_MAX_LEN];
        |                                                                                     ^^^^^^^^^^^^^^^
    ...
    284 | impl_Integer128!(I128_MAX_LEN => i128, U128_MAX_LEN => u128);
        | ------------------------------------------------------------- in this macro invocation

    error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
       --> github.com-1ecc6299db9ec823/itoa-1.0.1/src/lib.rs:251:89
        |
    251 |                         let buf2 = buf_ptr.offset(curr - U64_MAX_LEN as isize) as *mut [MaybeUninit<u8>; U64_MAX_LEN];
        |                                                                                         ^^^^^^^^^^^^^^^
    ...
    284 | impl_Integer128!(I128_MAX_LEN => i128, U128_MAX_LEN => u128);
        | ------------------------------------------------------------- in this macro invocation

    error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
     --> github.com-1ecc6299db9ec823/ryu-1.0.9/src/buffer/mod.rs:2:5
      |
    2 | use core::mem::MaybeUninit;
      |     ^^^^^^^^^^^^^^^^^^^^^^

    error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
      --> github.com-1ecc6299db9ec823/ryu-1.0.9/src/buffer/mod.rs:21:13
       |
    21 |     bytes: [MaybeUninit<u8>; 24],
       |             ^^^^^^^^^^^^^^^

    error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
      --> github.com-1ecc6299db9ec823/ryu-1.0.9/src/buffer/mod.rs:30:22
       |
    30 |         let bytes = [MaybeUninit::<u8>::uninit(); 24];
       |                      ^^^^^^^^^^^^^^^^^^^^^^^^^

    error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
      --> github.com-1ecc6299db9ec823/ryu-1.0.9/src/d2s.rs:27:5
       |
    27 | use core::mem::MaybeUninit;
       |     ^^^^^^^^^^^^^^^^^^^^^^

    error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
       --> github.com-1ecc6299db9ec823/ryu-1.0.9/src/d2s.rs:117:43
        |
    117 |     let mut vp_uninit: MaybeUninit<u64> = MaybeUninit::uninit();
        |                                           ^^^^^^^^^^^^^^^^^^^

    error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
       --> github.com-1ecc6299db9ec823/ryu-1.0.9/src/d2s.rs:117:24
        |
    117 |     let mut vp_uninit: MaybeUninit<u64> = MaybeUninit::uninit();
        |                        ^^^^^^^^^^^^^^^^

    error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
       --> github.com-1ecc6299db9ec823/ryu-1.0.9/src/d2s.rs:118:43
        |
    118 |     let mut vm_uninit: MaybeUninit<u64> = MaybeUninit::uninit();
        |                                           ^^^^^^^^^^^^^^^^^^^

    error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
       --> github.com-1ecc6299db9ec823/ryu-1.0.9/src/d2s.rs:118:24
        |
    118 |     let mut vm_uninit: MaybeUninit<u64> = MaybeUninit::uninit();
        |                        ^^^^^^^^^^^^^^^^

    error[E0658]: use of unstable library feature 'alloc': this library is unlikely to be stabilized in its current form or name (see issue #27783)
       --> github.com-1ecc6299db9ec823/once_cell-1.10.0/src/lib.rs:328:1
        |
    328 | extern crate alloc;
        | ^^^^^^^^^^^^^^^^^^^

    error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
       --> github.com-1ecc6299db9ec823/ryu-1.0.9/src/d2s.rs:140:27
        |
    140 |                 vp_uninit.as_mut_ptr(),
        |                           ^^^^^^^^^^

    error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
       --> github.com-1ecc6299db9ec823/ryu-1.0.9/src/d2s.rs:141:27
        |
    141 |                 vm_uninit.as_mut_ptr(),
        |                           ^^^^^^^^^^

    error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
       --> github.com-1ecc6299db9ec823/ryu-1.0.9/src/d2s.rs:145:33
        |
    145 |         vp = unsafe { vp_uninit.assume_init() };
        |                                 ^^^^^^^^^^^

    error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
       --> github.com-1ecc6299db9ec823/ryu-1.0.9/src/d2s.rs:146:33
        |
    146 |         vm = unsafe { vm_uninit.assume_init() };
        |                                 ^^^^^^^^^^^

    error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
       --> github.com-1ecc6299db9ec823/ryu-1.0.9/src/d2s.rs:182:27
        |
    182 |                 vp_uninit.as_mut_ptr(),
        |                           ^^^^^^^^^^

    error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
       --> github.com-1ecc6299db9ec823/ryu-1.0.9/src/d2s.rs:183:27
        |
    183 |                 vm_uninit.as_mut_ptr(),
        |                           ^^^^^^^^^^

    error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
       --> github.com-1ecc6299db9ec823/ryu-1.0.9/src/d2s.rs:187:33
        |
    187 |         vp = unsafe { vp_uninit.assume_init() };
        |                                 ^^^^^^^^^^^

    error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
       --> github.com-1ecc6299db9ec823/ryu-1.0.9/src/d2s.rs:188:33
        |
    188 |         vm = unsafe { vm_uninit.assume_init() };
        |                                 ^^^^^^^^^^^